services:
  mongodb:
    image: mongo:latest
    container_name: ar-blog-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - ar-blog
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  server:
    image: juneink/ar-blog-server:latest
    container_name: ar-blog-server
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=server
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - mongodb
    networks:
      - ar-blog
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  ar-blog:
    name: ar-blog

volumes:
  mongodb_data:
    name: ar-blog-mongodb-data
